//! The termist daemon: PTYs, sessions, status, local socket server.
pub mod claude;
pub mod codex;
pub mod github;
pub mod hook_client;
pub mod hookcmd;
pub mod launch;
pub mod logging;
pub mod mirror;
pub mod models;
pub mod opencode;
pub mod place;
pub mod registry;
pub mod resolve;
pub mod server;
pub mod session;
pub mod store;
pub mod transcript;
pub mod worktrees;
