[package]
name = "termist-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
termist-core.workspace = true
termist-platform.workspace = true
anyhow.workspace = true
ratatui.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
insta.workspace = true
interprocess.workspace = true
tempfile.workspace = true
